In [1]:
import matplotlib.pyplot as plt
import keras_ocr
import cv2
import math
import numpy as np

In [2]:
def midpoint(x1, y1, x2, y2):
    x_mid = int((x1+x2)/2)
    y_mid = int((y1+y2)/2)
    return(x_mid, y_mid)

In [3]:
def inpaint_text(img_path, pipeline):
    img = keras_ocr.tools.read(img_path)
    prediction_groups = pipeline.recognize([img])
    
    mask = np.zeros(img.shape[:2], dtype = "uint8")
    for box in prediction_groups[0]:
        x0, y0 = box[1][0]
        x1, y1 = box[1][1]
        x2, y2 = box[1][2]
        x3, y3 = box[1][3]
        
        x_mid0, y_mid0 = midpoint(x1, y1, x2, y2)
        x_mid1, y_mid1 = midpoint(x0, y0, x3, y3)
        
        thikness = int(math.sqrt((x2-x1)**2 + (y2-y1)**2))
        
        cv2.line(mask, (x_mid0, y_mid0), (x_mid1, y_mid1), 255, thikness)
        inpainted_img = cv2.inpaint(img, mask, 7, cv2.INPAINT_NS)
    
    return(inpainted_img)

In [4]:
pipeline = keras_ocr.pipeline.Pipeline()

img_text_remove = inpaint_text('rembg_test.png', pipeline)

Looking for C:\Users\ksuloko\.keras-ocr\craft_mlt_25k.h5
Looking for C:\Users\ksuloko\.keras-ocr\crnn_kurapan.h5
12/12 [==============================] - 58s 5s/step


In [5]:
print(img_text_remove)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [16]:
# plt.show(img_text_remove.any())

In [6]:
img_text_remove = cv2.cvtColor(img_text_remove, cv2.COLOR_BGR2RGB)

In [8]:
cv2.imwrite("text_remove.png", img_text_remove)

True